[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace", priority = 0 },
  { id = "end-of-file-fixer", priority = 1 },
  { id = "mixed-line-ending", priority = 2 },
  { id = "check-merge-conflict", priority = 100 },
  { id = "check-added-large-files", priority = 100 },
  { id = "check-executables-have-shebangs", priority = 100 },
  { id = "check-shebang-scripts-are-executable", priority = 100 },
  { id = "check-case-conflict", priority = 100 },
  { id = "check-symlinks", priority = 100 },
  { id = "detect-private-key", priority = 100 },
  { id = "check-json", priority = 100 },
  { id = "check-toml", priority = 100 },
  { id = "check-yaml", priority = 100 },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.48.0"
hooks = [{ id = "typos", args = ["--force-exclude"], priority = 100 }]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"
hooks = [{ id = "actionlint-system", priority = 11 }]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "v1.27.0"
hooks = [{ id = "zizmor", args = ["--min-severity", "high"], priority = 11 }]

[[repos]]
repo = "https://github.com/evanpurkhiser/prek-personal"
rev = "v1.0.2"
hooks = [
  { id = "gofmt-system", priority = 10 },
  { id = "shfmt-system", priority = 10 },
  { id = "golangci-lint-system", priority = 11 },
  { id = "shellcheck-system", priority = 11 },
]
